# Generated by Django 5.0.8 on 2024-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_external_user_id_user_signature_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizen_identification',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
