# Generated by Django 5.0.8 on 2024-10-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_citizen_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signature_images',
        ),
    ]
