# Generated by Django 5.0.8 on 2024-10-02 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_category',
            field=models.CharField(blank=True, choices=[('signing_document', 'signing_document'), ('normal_document', 'normal_document')], default='normal_document', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('signature_status', models.CharField(blank=True, choices=[('signed', 'signed'), ('unsigned', 'unsigned')], default='unsigned', max_length=50, null=True)),
                ('is_signature_visible', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='signers',
            field=models.ManyToManyField(related_name='signed_documents', through='documents.DocumentSignature', to=settings.AUTH_USER_MODEL),
        ),
    ]
