# Generated by Django 5.0.8 on 2024-10-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_document_category_documentsignature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attachment_documents',
            field=models.ManyToManyField(blank=True, related_name='attached_documents', to='documents.document'),
        ),
    ]
