# Generated by Django 5.0.8 on 2024-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentsignature_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsignature',
            name='signature_status',
            field=models.CharField(blank=True, choices=[('signed', 'signed'), ('unsigned', 'unsigned'), ('pending', 'pending'), ('timeout', 'timeout'), ('rejected', 'rejected'), ('failed', 'failed')], default='unsigned', max_length=50, null=True),
        ),
    ]
