# Generated by Django 5.0.8 on 2024-09-04 09:58

import edms.assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=edms.assets.models.get_path_files),
        ),
    ]
