# Generated by Django 5.0.8 on 2024-10-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(blank=True, choices=[('attachment', 'attachment'), ('appendix', 'appendix'), ('signature_file', 'signature_file')], default='attachment', max_length=255, null=True),
        ),
    ]
