# Generated by Django 5.0.8 on 2024-10-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(blank=True, choices=[('attachment', 'attachment'), ('appendix', 'appendix'), ('signature_file', 'signature_file'), ('signature_image', 'signature_image')], default='attachment', max_length=255, null=True),
        ),
    ]
