# Generated by Django 5.0.8 on 2024-10-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_file_type'),
        ('documents', '0003_document_attachment_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_files', to='documents.document'),
        ),
    ]
