# Generated by Django 5.0.8 on 2024-11-18 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_asset_document'),
        ('meeting_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='meeting_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_schedule_files', to='meeting_schedule.meetingschedule'),
        ),
    ]
