# Generated by Django 5.0.8 on 2024-11-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_meeting_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
