volumes:
  edms_local_postgres_data: {}
  edms_local_postgres_data_backups: {}
  edms_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: edms_local_django
    container_name: edms_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: edms_production_postgres
    container_name: edms_local_postgres
    volumes:
      - edms_local_postgres_data:/var/lib/postgresql/data
      - edms_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'

  redis:
    image: docker.io/redis:6
    container_name: edms_local_redis

    volumes:
      - edms_local_redis_data:/data
    ports:
      - '6379:6379'

  celeryworker:
    <<: *django
    image: edms_local_celeryworker
    container_name: edms_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: edms_local_celerybeat
    container_name: edms_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: edms_local_flower
    container_name: edms_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
