# Generated by Django 5.0.8 on 2025-02-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingschedule',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
